name: waveprop_pytorch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - alsa-lib=1.2.3=h516909a_0
  - blas=1.0=mkl
  - blosc=1.21.0=h8c45485_0
  - bottleneck=1.3.2=py39hdd57654_1
  - brotli=1.0.9=he6710b0_2
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2021.10.8=ha878542_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.10.8=py39hf3d152e_1
  - cffi=1.14.6=py39h400218f_0
  - cfitsio=3.470=hf0d0db6_6
  - charls=2.2.0=h2531618_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cudatoolkit=11.1.1=h6406543_8
  - cudnn=8.2.1.32=h86fa8c9_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py39h27cfd23_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - dbus=1.13.6=h48d8840_2
  - expat=2.4.1=h9c3ff4c_0
  - ffmpeg=4.3.2=hca11adc_0
  - fontconfig=2.13.1=hba837de_1005
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h0708190_1
  - fsspec=2022.1.0=pyhd3eb1b0_0
  - future=0.18.2=py39hf3d152e_4
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h7b6447c_0
  - glib=2.68.3=h9c3ff4c_0
  - glib-tools=2.68.3=h9c3ff4c_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - harfbuzz=2.8.2=h83ec7ef_0
  - hdf5=1.10.6=nompi_h7c3c948_1111
  - icu=68.1=h58526e2_0
  - imagecodecs=2021.8.26=py39h4cda21f_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9d=h36c2ea0_0
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.3.1=py39h2531618_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.80.0=h0b77cf5_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglib=2.68.3=h3e27bee_0
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm11=11.1.0=hf817b99_2
  - libnghttp2=1.46.0=hce63b2e_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.5.1=py39hf3c14e0_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.16.0=h780b84a_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzopfli=1.0.3=he6710b0_0
  - locket=0.2.1=py39h06a4308_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - magma=2.5.4=ha9b7cf9_2
  - matplotlib-base=3.4.3=py39hbbc1b5f_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - munkres=1.1.4=py_0
  - mysql-common=8.0.25=ha770c72_0
  - mysql-libs=8.0.25=h935591d_0
  - nccl=2.11.4.1=h97a9cb7_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.6=he412f7d_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - ninja=1.10.2=h4bd325d_0
  - nspr=4.30=h9c3ff4c_0
  - nss=3.67=hb5efdd6_0
  - numexpr=2.8.1=py39h6abb31d_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.1=py39hf3d152e_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1m=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py39h8c16a72_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=7.2.0=py39h6f3857e_2
  - pip=21.2.4=py39h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=4.5.1=py39hef51801_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.9.0=cuda111py39hc274426_1
  - pytorch-gpu=1.9.0=cuda111py39h788eb59_1
  - pywavelets=1.1.1=py39h6323ea4_4
  - pyyaml=6.0=py39h7f8727e_1
  - qt=5.12.9=hda022c4_4
  - readline=8.1.2=h7f8727e_1
  - scikit-image=0.18.3=py39h51133e4_0
  - setuptools=58.0.4=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sleef=3.5.1=h7f98852_1
  - snappy=1.1.8=he6710b0_0
  - sqlite=3.37.0=hc218d9a_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.11=h1ccaba5_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.9.0=py39
  - torchvision=0.10.1=py39cuda111hcd06603_0_cuda
  - tornado=6.1=py39h27cfd23_0
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zfp=0.5.5=h295c915_6
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - black==21.12b0
    - charset-normalizer==2.0.10
    - click==8.0.3
    - fft-conv-pytorch==1.1.0
    - idna==3.3
    - joblib==1.1.0
    - matplotlib==3.3.4
    - mypy-extensions==0.4.3
    - numpy==1.19.5
    - pathspec==0.9.0
    - platformdirs==2.4.1
    - progressbar==2.5
    - pudb==2022.1
    - pyffs==2.2.1
    - pytest==7.0.0rc1
    - pytz==2021.3
    - requests==2.27.1
    - scikit-learn==1.0.2
    - scipy==1.5.4
    - sklearn==0.0
    - sphinx==2.1.2
    - sphinx-rtd-theme==0.4.3
    - threadpoolctl==3.0.0
    - tomli==1.2.3
    - urllib3==1.26.8
    - urwid==2.1.2
    - urwid-readline==0.13
prefix: /home/bezzam/miniconda3/envs/waveprop_pytorch
